### ISSUE TITLE
Announcement banner is obscured when view width is less than something

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1032]
Can something be done to make the banner slide down when the toolbar wraparound is toggled?

![2022-08-10_10-10-59](https://user-images.githubusercontent.com/313942/183923325-07a8836c-8ecb-47cf-9acb-0b6ff4860b51.gif)

**Comment by s-paquette** [comment]
I was able to tweak the level at which the site goes into 'collapsed' mode, i.e. because the bar will wrap like that it collapses it into a stack which is opened, like so:

![image](https://user-images.githubusercontent.com/8442808/185443728-567d84af-aead-4d5a-9e5b-bd2e2020e777.png)

The problem is by adding the additional BQ link we've made the banner have a minimum width of somewhere around 1600px. This is awfully large, even in this time of 4K monitors, so we may need to re-think some of the text next to the icons. Ideas:

* Change 'Exploration' to 'Explore'
* Change 'Documentation' to 'Docs'

We can also cut down some of the white-space next to the NCI logo; it doesn't need that massive whitespace they gave us.
