### ISSUE TITLE
Dash in collections search destroys Search Scope filters

### ISSUE THREAD

**Issue by wlongabaugh** [ImagingDataCommons/IDC-WebApp#1065]
Do a search on "CT-". As first pic shows, things are going great after entering two characters: "CT". And note the dash is present in a collection. Type in the "-", and second pic shows how everything falls apart. Delete the dash, and you are not back at a good place (third pic), as the filters are all messed up.
<img width="430" alt="SearchStep1" src="https://user-images.githubusercontent.com/8441547/195906880-121e6af8-4b65-4dc0-8cc2-33aedceec99f.png">
<img width="444" alt="SearchStep2" src="https://user-images.githubusercontent.com/8441547/195906897-3115bc53-1abe-4f85-8d69-2362d247284a.png">
<img width="449" alt="SearchStep3" src="https://user-images.githubusercontent.com/8441547/195906910-3a0017dd-0883-437e-8199-c3b17ea340c7.png">

**Comment by G-White-ISB** [comment]
There were 2 issues. 
1. The text string was searched against an internal representation of the collection names in which '-' is replaced by '_'.

2. If you entered a text search string that did not match any collection in a program or collection set, 'display-none' was added to the div containing that collection set. But 'display-none' was not removed from the div when the search string changed.
This will be fixed in the next PR
