### ISSUE TITLE
Change CancerType to no longer be case-corrected in display

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#1283]
<img width="688" alt="image" src="https://github.com/ImagingDataCommons/IDC-WebApp/assets/313942/12e53b5e-09a2-419e-b78c-ea7eececbc7b">

**Comment by s-paquette** [comment]
The issue here is CancerType was set to be adjusted for display purposes to case-correction, which was resulting in Ductal Adenocarcinoma and Ductal **a**denocarcinoma being considered the same value even though they're from different collections (htan_wustl and cptac_pda). 'Preformatted Values' has been turned on for CancerType in all databases, which will prevent this from happening in the future. @pgundluru @fedorov You should be able to see this on dev right now; Test will need to finish re-deploying to flush the UI cache so the change takes effect.

![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/8442808/e4f40304-97ba-4675-8a2a-decd2bb251b4)

**Comment by s-paquette** [comment]
Side note, we agreed for consistency to populate CancerType from collection_cancerType in dicom_all instead of original_collections_metadata going forward.

**Comment by fedorov** [comment]
So the sky didn't fall, fortunately.

I think we should make capitalization consistent for that one case in the tables when @bcli4d is back, and follow with similar updates if we discover such inconsistencies in the future.

I do not see reasons not to switch to turning off "shadow capitalization" in a future release.

**Comment by pgundluru** [comment]
The change with cancer type is reflected in test tier like below 
![image](https://github.com/ImagingDataCommons/IDC-WebApp/assets/85526819/aaea9a23-f862-4a3c-8831-bf1fc7a48147)

**Comment by fedorov** [comment]
Whenever @bcli4d gets to this (after v16) we should fix the capitalization in the collection-level table.
