### ISSUE TITLE
Need to revisit labels for the modality values

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#131]
@s-paquette @G-White-ISB can you tell me what is the procedure for mapping the values of Modality attribute to the items in the list below?

![image](https://user-images.githubusercontent.com/313942/85348442-9f2a5800-b4c9-11ea-866a-a1e13ab23c39.png)

@bcli4d and I have been putting together the list of various tables that will be needed by Suzanne [here](https://docs.google.com/document/d/14Wfu-q3hbRxlOSDGIWC0kkSI3CsYoKyB5EhmgY52TgM/edit#heading=h.2vcp5etu9x2o), and potentially the modality mapping should be formalized by another table?

**Comment by fedorov** [comment]
Mapping from the modality attribute to the values is here in the standard: http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.7.3.html#sect_C.7.3.1.1.1

**Comment by fedorov** [comment]
I think it would be much more useful and clean if instead of Modality we take SOPClassUID, which is a unique identifier that defines Information Object Definition for the DICOM object, and show name corresponding to the SOPClassUID in the UI. We already have a BQ table with this content: `idc-sandbox-000:DICOM_2019e.CIODs` - that table is populated directly from the standard, 
this view maps SOPClassUID to the IOD name: `idc-sandbox-DICOM_2019e.CIODs_name_and_UID`.

@dclunie what do you think about using `SOPClassUID` mapped to a human-readable name instead of `Modality`? Or should we show both to the user in the webapp?

**Comment by dclunie** [comment]
I am not sure that using SOP Class rather than Modality is what the user wants to see.

E.g., is their primary interest any MR images at all, or the difference between legacy single-frame, or Legacy Converted or true Enhanced MF SOP class images?

In clinical PACS, it is more common to browse/search by Modality, not SOP Class, and for the system/viewer to protect the user from encoding details behind the scenes.

I don't think you need both, in the main UI, since it will excessively stratify the studies/series, but t would be nice to be able to search/filter by (name of) SOP Class, if the user really wants to.

**Comment by fedorov** [comment]
Those are good points David. But I actually thought it might be of interest to know between enhanced and legacy enhanced, and I also thought about parametric maps, which are indistinguishable from source images based on Modality. But I don't think we have any parametric maps at the moment, so we can deal with this later.

Based on your response, let's just keep Modality updated to correct values.

**Comment by fedorov** [comment]
@s-paquette I see you updated the webapp - thank you! Small nitpick - can you change "Ctpt" to "CTPT"?

**Comment by s-paquette** [comment]
Ah, looks like Modality isn't flagged as preformatted--I'll do that from here on out.

**Comment by s-paquette** [comment]
@G-White-ISB George, the values are now coming through correctly, but it looks like the WebApp is massaging them somehow. This might be because the value CTPT isn't in the list from the webpage, but it IS in the dicom metadata table as a Modality value. So it probably shouldn't be massaged by the WebApp, just used as-given.

**Comment by fedorov** [comment]
@G-White-ISB @s-paquette also note that capitalization is inconsistent between the filter definition and the labels in the facet list: 

![image](https://user-images.githubusercontent.com/313942/86601923-f15e8500-bf6f-11ea-8516-b8d46b4e519f.png)

Related to this, don't we need a separate category (e.g., maybe "Project"?) for things like "QIN", "TCGA" - those are currently in the same category as individual collections, but I don't think they should be.

**Comment by fedorov** [comment]
> Related to this, don't we need a separate category (e.g., maybe "Project"?) for things like "QIN", "TCGA" - those are currently in the same category as individual collections, but I don't think they should be.

I factored that one out into a separate issue here: https://github.com/ImagingDataCommons/IDC-WebApp/issues/145

**Comment by s-paquette** [comment]
Modalities used per the provided link, and CTPT was put in by hand because it wasn't present.
