### ISSUE TITLE
Filter Application to Series and Studies

### ISSUE THREAD

**Issue by G-White-ISB** [ImagingDataCommons/IDC-WebApp#148]
It's a simple fix but we just need to make the decision. Should the filters apply only at a CASE or Patient level, OR  a CASE/Patient level AND Study Level? Once cases are filtered should all studies relevant to that case be available, or only studies that match the filter? I believe there is consensus that the filters do not apply at the Series Level. In other words if we filter for Cases that contain Seg modalitites we still want to view the   other Series with other Modalities.

**Comment by fedorov** [comment]
Yes, I believe it is more helpful to show all series in the studies that match.

I do think it is more helpful if filters apply both at the Patient and Study levels, but going forward we might want to revisit what we are counting. Maybe post-MVP we could think of a toggle that would count studies instead of cases?

**Comment by s-paquette** [comment]
We can count both at the same time and adjust which we show; that's fairly easy to do. The real question is about the data structure.

The issue we have right now is we're wanting to filter on attributes which aren't available at the study level, they're at the instance level (segmentations). As a result, we have to have the instances present. We can only collapse back down to series or study if we can be sure there's only one value per segmentation attribute per study or series. Otherwise, the breakout needs to be down to the lowest level that has data unique to it (instance, in this case).

**Comment by fedorov** [comment]
>  if ANY instance in the study matches, we return the study

I think this is it.

But indeed we are venturing into the area where the answer is not going to be obvious, and I will need to think about the technical details you discussed above. But I think returning the study if any instance matches, and listing all series that belong to the study, will be more helpful than what we have now. And if we could have an option to show counts of studies instead of cases to the user, that would be quite helpful as well.

Without going into the technical details, would it make sense to just run another query to get all the series that correspond to the selected study?

**Comment by fedorov** [comment]
Agreed not to filter series within the study

**Comment by G-White-ISB** [comment]
Changed in my next code commit tomorrow or Wed
