### ISSUE TITLE
"Study list" should be disabled for OHIF Viewer

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#164]
There is a setting to do this easily, @pieper or @swederik can point to the setting in config, if you cannot find it.

![image](https://user-images.githubusercontent.com/313942/87675762-c92c0e80-c745-11ea-89d7-37eeec9da6c0.png)

**Comment by wlongabaugh** [comment]
This button actually works now with the new config file...still drop it @fedorov ?

**Comment by fedorov** [comment]
@pieper can you provide the config setting to disable this? Or do you think we should keep it?

**Comment by pieper** [comment]
When we are ready to fork ohif it will be easy to go through and disable this and the annotation tools as requested in #171.

I think yes, we should disable the study list because it doesn't sort as one would expect.  At some point we should be able to provide the selected cohort in a similar sort of list and bring up ohif on any of the studies in the cohort, right?  Makes the most sense for me if ohif is always just a new tab that pops up and you just close the tab when you are ready to go back to your cohort.

**Comment by fedorov** [comment]
@pieper can you disable it, now that we have the fork?

**Comment by pieper** [comment]
It turns out this is already a configure option.  @G-White-ISB can you add the highlighted line below to the appconfig for IDC's OHIF deployment?

```
window.config = {
  routerBasename: '/',
  showStudyList: false,  <------
...
```

**Comment by wlongabaugh** [comment]
New deployments take care of this.
