### ISSUE TITLE
 non-parameterized BQ query corresponding to the current cohort

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#182]
Follow up from #54

As discussed with @s-paquette, it should be quite easy to add a button to the portal that would allow user to get the non-parameterized BQ query corresponding to the current cohort. @s-paquette should this be in a separate issue, or keep the current one open?

**Comment by fedorov** [comment]
Also related to #394

**Comment by fedorov** [comment]
@s-paquette what is the status of this issue? I thought it has been prioritized quite some time ago, but I do not see any updates.

**Comment by fedorov** [comment]
Suggestion to have a collapsed by default area in the Filter definition, which could be expanded, and a button to copy the query. Wording could be eg "Equivalent SQL query".

**Comment by s-paquette** [comment]
@fedorov A first pass at this is now available on dev and test. A button displays on the cohort details page which will open a dialog with the formatted query, and provides a button to click for copying all the text. A couple of caveats:
- There are very few formatters available for BQ syntax at the moment, so I'm using one in SQL mode with a few regex replacements to get it looking correct.
- The table names will be relative to the tier you're viewing it on; you'll see `idc-dev-etl` and so on for dev and test because that's where we point those tiers.
- I'm defaulting to a somewhat 'standard' set of fields (PatientID, collection_id, StudyInstanceUID, SeriesInstanceUID, etc.) but we can add others. This seemed like a reasonable starting point for a user to edit.

**Comment by s-paquette** [comment]
Have now added a button to the cohort list page; this allows a user access to older data version cohorts. The issue here is this requires a server call to resolve the old data version tables and formulate the query; it's relatively fast, however.

**Comment by fedorov** [comment]
This is great, I think this is what we needed! I think it would be good to include SOPInstance in the query to make result similar to the cohort export from the portal. I am not sure if I messed something up when I tried to compare, or there is a real difference, but if I set the filter "Modality=CT", I am getting 31,087,657 rows when the cohort is exported into BQ from the portal, and 31,093,803 when I run the query provided in the portal. I would expect the result to be the same. Below is the query I modified to include SOPInstanceUID

```
SELECT
  dicom_pivot_v7.PatientID,
  dicom_pivot_v7.collection_id,
  dicom_pivot_v7.source_DOI,
  dicom_pivot_v7.StudyInstanceUID,
  dicom_pivot_v7.SeriesInstanceUID,
  dicom_pivot_v7.Modality,  
  dicom_pivot_v7.SOPInstanceUID
FROM
  `idc-dev-etl.idc_v7.dicom_pivot_v7` dicom_pivot_v7
WHERE
  StudyInstanceUID IN (
    SELECT
      StudyInstanceUID
    FROM
      `idc-dev-etl.idc_v7.dicom_pivot_v7` dicom_pivot_v7
    WHERE
      (LOWER(dicom_pivot_v7.Modality) LIKE LOWER('CT'))
    GROUP BY
      StudyInstanceUID
  )


ORDER BY
  dicom_pivot_v7.PatientID ASC,
  dicom_pivot_v7.collection_id ASC,
  dicom_pivot_v7.source_DOI ASC,
  dicom_pivot_v7.StudyInstanceUID ASC,
  dicom_pivot_v7.SeriesInstanceUID ASC,
  dicom_pivot_v7.Modality

**Comment by fedorov** [comment]
Also, in this part below - shouldn't this be select `PatientID` instead of `StudyInstanceUID`, since we define cohorts in terms of cases that match the filter?

```
    SELECT
      StudyInstanceUID
    FROM
      `idc-dev-etl.idc_v7.dicom_pivot_v7` dicom_pivot_v7
    WHERE
      (LOWER(dicom_pivot_v7.Modality) LIKE LOWER('CT'))
    GROUP BY
      StudyInstanceUID

**Comment by fedorov** [comment]
Also, can you clarify why it is `LIKE` and not `=`?

**Comment by s-paquette** [comment]
> Also, in this part below - shouldn't this be select `PatientID` instead of `StudyInstanceUID`, since we define cohorts in terms of cases that match the filter?

We define the cohort in terms of Study, not case. The counts on the exploration page are cases, but the cohort itself is by study.

> This is great, I think this is what we needed! I think it would be good to include SOPInstance in the query to make result similar to the cohort export from the portal. I am not sure if I messed something up when I tried to compare, or there is a real difference, but if I set the filter "Modality=CT", I am getting 31,087,657 rows when the cohort is exported into BQ from the portal, and 31,093,803 when I run the query provided in the portal (in both cases I did this on the test tier). I would expect the result to be the same. Below is the query I modified to include SOPInstanceUID

That's due to the export query including a GROUP BY statement. If you add this to your query above, the counts will match:
```GROUP BY
  dicom_pivot_v7.PatientID,
  dicom_pivot_v7.collection_id,
  dicom_pivot_v7.source_DOI,
  dicom_pivot_v7.StudyInstanceUID,
  dicom_pivot_v7.SeriesInstanceUID,
  dicom_pivot_v7.Modality,  
  dicom_pivot_v7.SOPInstanceUID```

We can put a GROUP BY into this query by default, it just doesn't do that due to not being an export-specific query.

> Also, can you clarify why it is `LIKE` and not `=`?

Because BigQuery is case sensitive and MySQL isn't, we default to full case insensitivity via LOWER() and LIKE. (Since the user can't put in a custom filter in our backend, LIKE functions the same as = for our purposes as we don't use any wildcards ourselves.) We *could* switch it to = but in our use case that's less likely to make a difference. (LIKE-without-wildcards is often optimized into = on the backend.)

**Comment by s-paquette** [comment]
@fedorov Actually, when I look at any cohort query, I see a GROUP BY clause--there's a blank spot in your query where one would have been. That's what was keeping the row counts the same.

**Comment by s-paquette** [comment]
@fedorov Added SOPInstanceUID to the query, this is now available in dev and test. Let me know if you're still not getting a GROUP BY clause so I can see about replicating that behavior.

**Comment by fedorov** [comment]
Thank you. It might be that I just failed to include the `GROUP BY` part by mistake. 

@pgundluru when you test this, please include a test to confirm the cohort defined by the query matches the one exported directly from the portal.

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/152442608-6419dba2-2b02-43be-b98d-87a1f39c3c39.png)
