### ISSUE TITLE
Applying quantitative filters does not filter at the case level

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#184]
If I adjust any of the quantitative measurements filters, filtering results are returned at the series, not case level.

To reproduce, try to set anything, like Diameter to any constraints. Result is SR is the only modality available in the result:

![image](https://user-images.githubusercontent.com/313942/89334168-1b38c380-d664-11ea-9c39-43f2dfd6f157.png)

This cannot be correct, since every single diameter measurement (at least for our dataset) is accompanied by a segmentation and the image on which that segmentation was done.

If I limit by, for example, anatomic region, or qualitative measurements, I correctly get filtering results at the case level:

![image](https://user-images.githubusercontent.com/313942/89334397-723e9880-d664-11ea-9917-b3880f87f42e.png)

**Comment by fedorov** [comment]
Confirming the issue is still present as of today in idc-dev.

**Comment by wlongabaugh** [comment]
Question is what do we want the filter to mean? Need to explain to user what filter means?

**Comment by wlongabaugh** [comment]
This is what caused pie charts to behave differently.

**Comment by wlongabaugh** [comment]
Add documentation to describe this.

**Comment by fedorov** [comment]
Ok, I don't know if it works or not - all I know I cannot make sense of it. So I guess I am not the right person to tell if it works or not, because I just have no clue about what to expect. Sorry.

Here's the configuration:

![image](https://user-images.githubusercontent.com/313942/91788326-eb84c900-ebd9-11ea-8fae-864e66ef8d74.png)

So I selected "None", and "None" has 2 cases. Then why do I have 123 cases in the cohort?

![image](https://user-images.githubusercontent.com/313942/91788366-05261080-ebda-11ea-9c03-05cc9d668452.png)

How about you guys write documentation about what is the expected behavior of the app, and then I test it against that expected behavior?

**Comment by G-White-ISB** [comment]
No this is a bug. The 'None' filter is not working for derived tab attributes.

**Comment by s-paquette** [comment]
So, once again, it's a question of what selecting an attribute should mean. Like related, are Derived attribute filters ONLY ever applied to records with derived data? Are they only applied to records with that specific category of derived data?

**Comment by fedorov** [comment]
@s-paquette is it still about what they **should** mean, or about what they **do** mean right now?

I mean, they should mean something right now - do we have an explanation for the currently observed behavior? Is this a bug or not?

I have to say it is concerning that even among developers there does not seem to be an agreement whether what we have right now in the interface is correct or not correct.

**Comment by s-paquette** [comment]
What's happening right now is any record with a null in one of the derived fields is returned, but that effectively means all of them since most cases have records with null values for derived data. As with related, we can change the filtering to mean 'has derived data but doesn't have this field filled out', if that makes more sense.

**Comment by fedorov** [comment]
> What's happening right now is any record with a null in one of the derived fields is returned, but that effectively means all of them since most cases have records with null values for derived data. 

In this case, why is the left side showing 2 as the number of cases that have "None"? Or the meaning of "None" is different between counting cases on the left and selecting cases on the right?

**Comment by s-paquette** [comment]
The counts show a number because we're counting derived only AS derived; which is to say, derived filters only apply to derived records for purposes of counts. We can also filter that way, as we do now for related data, if we want.

**Comment by fedorov** [comment]
Suzanne, I am sorry, I think I am lost.

If you believe the current behavior is as expected, can you please summarize it in a form of end-user documentation that would explain the current behavior?

**Comment by s-paquette** [comment]
I'll be honest, I don't know the data itself nearly well enough to write end-user documentation. I can take a stab at it, but the text is likely to be off. Effectively:

Facets are counted by case, with filters on attributes from related data sets only applying to cases which have those data. For counting purposes, all instance records from a study which contains *at least one instance record* that matches the filter are included.

**Comment by G-White-ISB** [comment]
Well what about a technical explanation for one example? Is it still possible to explain this with Big Query or would one need to understand SOLR? If the only filter is ANATOMIC REGION IN NONE, then what are the queries to 1) count attributes in Modality? and 2) count attributes in Anatomic Region?

Could we drop the None category in the UI for now?

**Comment by s-paquette** [comment]
It's less about Big Query vs. Solr, because you would have this problem in BigQuery as well. Derived data are in their own views--so, are those views joined in using INNER JOIN, or LEFT JOIN? And as the pair of queries discussed on discourse show, there's a distinct difference between using the filter to pull records from a study, and using it to pull just instance records. That will be an issue regardless of the platform used to count.

(It's actually much easier to write count queries in Solr, since it's designed for faceted counting; faceted counting in SQL is a lot more onerous when you want to filter.)

Regarding an AnatomicRegion filter, the question again is--should that only apply to records with derived data? Or should it apply to all records, which means only records with derived data will have counts, and everything else goes to 0?

**Comment by G-White-ISB** [comment]
I understand there are ambiguities and design issues in faceted counting. I am not trying to debate those right now. I just want to follow what is CURRENTLY implemented ... what is your recipe right now? 

I only brought up Biq Query because Andrey and I understand it better than SOLR. Could you write a couple of queries that yield the same numbers for a couple attributes that we see in the web app right now? Could you make the light bulbs appear over our heads? That might be easier for you than writing user documentation.

**Comment by s-paquette** [comment]
Can we move this discussion to Discourse, where we have a similar thread?

**Comment by G-White-ISB** [comment]
sure

**Comment by fedorov** [comment]
This behavior is fixed now

![image](https://user-images.githubusercontent.com/313942/93801105-84be6280-fc0f-11ea-8b6d-21dd7529206e.png)
