### ISSUE TITLE
Study/series tables selection behavior should be consistent

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#203]
Follow up on https://github.com/ImagingDataCommons/IDC-WebApp/issues/79

There is currently an inconsistency in clicking behavior between study and series tables: in the study table, to open the study user needs to click on the study UID, while in the series table, it is ok to click anywhere on the row.  Is there a reason for this inconsistency?

**Comment by fedorov** [comment]
Discussed this issue and decided it would be more intuitive to load selection with a separate button instead of clicking on rows/UIDs.

**Comment by wlongabaugh** [comment]
We added a separate button _to each row_ to replace the different link in different columns in different tables, to make the action clear and unambiguous. Unfortunately, there was some difference in interpretation of the statement "...a separate button instead of clicking on rows/UIDs." Sorry. We can consider a single launch button post MVP, but that is more than just a UI rearrangement that maintains existing functionality.
