### ISSUE TITLE
Incorrect filtering results for qualitative analysis

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#212]
I was testing on dev, and if I select Anatomic region = Chest, I get all zeros for all of the qualitative analysis results. I know this is incorrect because the LIDC cases are included, and all of them have qualitative analysis results.

**Comment by s-paquette** [comment]
This is happening for the same reason that selecting a derived attribute would zero out the original records--the segmentation records don't have qualitative values, hence the zeros.

It's sounding more and more like the index shouldn't be SOP instance record based. Is the intention that selecting a filter selects the study? The series? Because right now, it selects the instance level record.

**Comment by fedorov** [comment]
I always thought the facet selects a case, not study, series or instance.

**Comment by s-paquette** [comment]
The BQ table being supplied to build the index is SOP Instance records, so that's what's selected. We would need to reconstruct the source data in order for cases to be 'selected' and then counted.

**Comment by fedorov** [comment]
Ok, so apparently there was miscommunication, since from the start I thought we are counting cases, and I did not realize the culprit is on the BQ side.

I am guessing at this point it is not feasible to fix this for the MVP, so the least we can do is to document for the users the current behavior of the system without getting into the discussions about the internals. Could you do that? I am not sure I would be able to, I have troubles understanding it myself. 

I also do not understand why quantitative measurements are not zeroed out, but qualitative are. Both are organized the same way in BQ tables.

**Comment by s-paquette** [comment]
Although we *are* counting cases,

**Comment by fedorov** [comment]
> in order to do so the data has to be structured accordingly

Can you formulate the requirements of how the data should be structured?

**Comment by s-paquette** [comment]
This will depend on how we expect the counting to function. In other words, what do we think users want to actually apply the filter *to*--cases? (Or series, or studies...) If it's cases, then the data needs to be arranged by case; in other words, a given case has only *one* row in the index, and then a long series of fields summarizing the various data in its available records. Eg. modality would actually be a list of ALL modalities available for that case, across study and series. If all we're counting is the case, we don't care WHICH instance it's from, just that it's in there.

We can then maintain a completely separate per-instance index which is for producing the tables users click on to open OHIF. Those are simply queries in a straight forward 'give me some records' manner; there's no counting being done there.

**Comment by fedorov** [comment]
Ok, I need to think about this. I wish we had this discussion earlier than 1 month before the MVP release.

**Comment by fedorov** [comment]
@s-paquette I think we need to set the time to discuss this. I will follow up on Slack.

**Comment by s-paquette** [comment]
I should be free to discuss it possible next week. Right now I'm focused on the homepage and cohort saving.

Regarding the questions:

- More than one table would still be combined into a single index, because joining across indicies is incredibly bad for performance.
- Cells *can* be multivalued but they can't be formal object types. So, lists, in the sense that there's a basic delimiter specified like a space or a comma, something to tokenize on. 

*Most* of our current fields should? combine cleanly. The big issue will be the numeric and date fields; those would have to become truly 'multivalued' and indexing them may prove tricky. I need to do some research into how this is handled in Lucene/Solr and then we'll have a better idea.

**Comment by s-paquette** [comment]
@fedorov Although...to back up to the original comment, I don't see 'Chest' in Anatomic Region. Do you mean Body Part Examined?

**Comment by s-paquette** [comment]
@fedorov Okay to close this one for now? We can open a new ticket for re-organization of faceted data.

**Comment by s-paquette** [comment]
For reference:

A shim was placed to relate the Original attribute records *back* to the Derived attribute records, the same way derived records relate to Original records. (I.e. the subquery was only happening when Derived facets are selected; now it will happen for both). 

Going forward we'll want to reformat the data we count to be central to the *kind* of counting we're doing, i.e., if we're counting cases, the records need to be by-case and all duplicated fields combined into either a single text field (for strings) or multi-valued fields with a delimiter (for numerics).
