### ISSUE TITLE
Improve style and attractiveness of the gallery box on the front page

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#230]
the grey box with the images looks quite ugly, and the resizing and
fitting of the image in that box often leaves a lot of gray space
around the image. What are the constraints on what you can and cannot
do on the front page? What toolkits or frameworks you are able to use,
so I can try to find a design/element that you can implement?

**Comment by s-paquette** [comment]
Regarding the images--we can certainly change the color of the box housing the image. That's just what I was given to work with. There are several issues at play here:

1. Sapiens cannot be resized.
2. It's on the right.

This results in a very awkward problem which isn't related to any framework; it's that everything around sapiens has to move while it doesn't. However, I was also asked to keep it taller than the image box--also a problem as they're in the same row and we want them aligned--and the images themselves are quite short and tall as opposed to long. 

I'll note that this is almost for sure why sapiens is on the *left* on the PDC page and not in the right. It makes it much easier to reflow and layout the page. (Compare to GDC, which doesn't handle it at all, and as a result their page can't be displayed at smaller size at all.)

This isn't something which can be solved without essentially rewriting sapiens. Not sure we want to get into that even as a post-MVP item, but it's something we can think about. Again, there's a reason PDC put it in the left, and GDC's page displays badly with it on the right. If we want the page to responsively resize instead of scrolling, and if we was sapiens on the right, this is where we're at.

**Comment by fedorov** [comment]
FWIW, it is completely fine with me if sapiens is on the left.

**Comment by fedorov** [comment]
> I'll note that this is almost for sure why sapiens is on the left on the PDC page and not in the right. It makes it much easier to reflow and layout the page. 

@wlongabaugh do you have any reason to keep sapiens on the right? Shall we make Suzanne's life easier by moving it to the left?

**Comment by s-paquette** [comment]
A couple of floating image card type options I threw together between working on cohort code:

![option_1](https://user-images.githubusercontent.com/8442808/91249369-96dddb80-e70b-11ea-8fba-fe4bf63de0db.png)
![option_2](https://user-images.githubusercontent.com/8442808/91249371-980f0880-e70b-11ea-95c1-2130fa0dd69f.png)

This is just to give you an idea of ways it could look. I've set these up in the CSS as option1 and option2 so it's easy to flip between them and pick colors based on what Alison suggests or folks want.

**Comment by pieper** [comment]
Wow, cool, yes, we need more of this 👍

**Comment by fedorov** [comment]
Suzanne, I think those floating cards look better than what we had before. Thank you! I would let Alison look and comment on how to improve further.

**Comment by fedorov** [comment]
Suzanne, what is the icon set from where the Discourse and Documentation icons are coming from?

**Comment by fedorov** [comment]
For the future - nice example of a tabbed floating card: https://datacommons.cancer.gov/ (just because I was looking at that page and noticed it).

**Comment by s-paquette** [comment]
The good news is Bootstrap already supports this. So, here's what I'm handing off to Mi:

Option 1:
![image](https://user-images.githubusercontent.com/8442808/91355969-c6d8bd80-e7a3-11ea-8b8e-c5ed587b0b5e.png)


Option 2:
![image](https://user-images.githubusercontent.com/8442808/91355957-c3453680-e7a3-11ea-99fe-b0f99d704ef2.png)

The primary difference here is Option 1 makes use of a box drop shadow that gives it a sort of hovering effect, but this effect comes at the cost of no border. Option 2 is a flatter, simpler look which is somewhat in vogue right now. 

Swapping between them is a single character change in the class of the container. Mi can fiddle as you guys prefer; I'll put it live with Option 2 for now.

**Comment by s-paquette** [comment]
@fedorov Missed this question earlier:

> Suzanne, what is the icon set from where the Discourse and Documentation icons are coming from?

Font-Awesome, Free version (we use this throughout the site). There are also glyphs available with Bootstrap itself:

https://getbootstrap.com/docs/3.3/components/#glyphicons

**Comment by fedorov** [comment]
Thanks!

How about we use one of those for collections: 
![image](https://user-images.githubusercontent.com/313942/91469607-99524980-e861-11ea-9cfd-1945a0d20e51.png)
![image](https://user-images.githubusercontent.com/313942/91469761-d1598c80-e861-11ea-8a26-5a91b098cc1b.png)

this for exploration:

![image](https://user-images.githubusercontent.com/313942/91469722-c1da4380-e861-11ea-9113-bb6a5d75fe5b.png)

Somehow I did not see the icons that you use for discourse and documentation in that list - maybe I missed them.

Also, the login icon looks a bit different from what you have:

![image](https://user-images.githubusercontent.com/313942/91469978-20072680-e862-11ea-8bff-7a8b5af74692.png)

**Comment by fedorov** [comment]
I just think it will look cleaner if we use a consistent set of icons throughout the site

**Comment by s-paquette** [comment]
Font Awesome is here:

https://fontawesome.com/icons?d=gallery&m=free

We can definitely switch to those; they were used because that's what's on the other two sites.

**Comment by fedorov** [comment]
Sorry, I mis-read the previous comment. I am fine with any collection of icons, I am just suggesting all of the icons in the header come from the same collection. I will make another issue, since we diverged from the topic of this one.
