### ISSUE TITLE
Selection of the series will return the error message, "ViewerMain: Cannot read property 'SeriesInstanceUID' of undefined"

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#238]
On the dev tier the selection of the series description, VOI PE Segmentation thresh=70 will return a,  "ViewerMain: Cannot read property 'SeriesInstanceUID' of undefined." ISPY1 is the related collection. 

<img width="960" alt="2020-08-27 (2)" src="https://user-images.githubusercontent.com/16824894/91486835-d2e37e80-e87a-11ea-9033-960c1d13486f.png">

<img width="960" alt="2020-08-27 (3)" src="https://user-images.githubusercontent.com/16824894/91487082-38d00600-e87b-11ea-8b37-8e6503fd4f10.png">

**Comment by madelyngreyes** [comment]
Also, the collection qin_headneck seems return an error "ViewerMain: Referenced series for SEG dataset not present." 

<img width="960" alt="2020-08-27 (6)" src="https://user-images.githubusercontent.com/16824894/91490054-d6c5cf80-e87f-11ea-96d4-1a7593c1c2f6.png">

<img width="960" alt="2020-08-27 (5)" src="https://user-images.githubusercontent.com/16824894/91490042-d3cadf00-e87f-11ea-9e67-da47ec24a8b2.png">

**Comment by pieper** [comment]
@s-paquette let us know if you think this is an OHIF issue.

**Comment by s-paquette** [comment]
...certainly sounds like it. All we do is send along a UID, we don't really DO anything else. @wlongabaugh This isn't possibly proxy-related, is it?

**Comment by fedorov** [comment]
@madelyngreyes in both cases you seem to be trying to open a SEG series, not study, which is not expected to work, and that is the ultimate source of the error. So the real bug is that IDC allows this to happen, not that it happens per se.

This is because you are trying to open a SEG series, and so OHIF does not have the reference since the URL ends with something like `1.3.6.1.4.1.14519.5.2.1.6279.6001.185810436275168701789786930141?SeriesInstanceUID=1.2.276.0.7230010.3.1.3.0.89838.1553284405.300965`. This is expected, and the right way to handle it would be to pass the reference series in the URL, but that's post MVP for sure. Next level down would be to not allow opening series that cannot be opened, but my guess is that is also post MVP.

**Comment by fedorov** [comment]
For the MVP, we should turn off the button that corresponds to the series of types SEG or RTSTRUCT.

**Comment by fedorov** [comment]
My preference is grayed out button with tooltip "Please open at the study level to see this series"

**Comment by G-White-ISB** [comment]
In progress.

**Comment by fedorov** [comment]
Selection of non-imaging series is disabled
