### ISSUE TITLE
Incorrect cohort summary plots

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#240]
See issue described in https://discourse.canceridc.dev/t/understanding-idc-portal-cohort-plots/81.

**Comment by s-paquette** [comment]
I want to note that this isn't really a bug--this is case centric counting. So if we want the counts to function in some other manner--Study centric, for example--then we need to do things differently.

**Comment by s-paquette** [comment]
I think I wound up mentioning all of this in a different ticket, but here are the things we need to answer before we can change this:

- What are the numbers we want counted--cases, or studies?
- What are we aggregating those numbers based on--*studies* filtered using the filters, or *cases*? 
  - If we count by case, then selecting eg. a modality indicates you want the case counts for all *cases* with any instance that has a given modality. This means all the other case counts will be for instances which are from those cases. (This is how it currently works.)
  - If we count by study, then selecting eg. a modality indicates you want the case counts for all *studies* which have instances that have the given modality. This means all the other case counts will be for instances which are from those *studies*.

Is the later how we want to count? (Or, do we want to count in some other way?)

**Comment by fedorov** [comment]
Ok, I thought that through the discussion on the forum you confirmed that this is a bug:

> Sorry I misread–I think I understand what you’re saying. And to be clear, it’s cases. We don’t count studies.
>
> …ah ha. This is due to how we wanted to make Original data ‘child record case search’ against derived. It’s also applying it to other Original data records. Since I’m working on counting related separately (same code) I’ll see if I can sort out a way to only go between orginal/derived and not original/original.

If this is not a bug, can you please explain how the current interface counts cases?

The issue is what I described in the forum, I did not see an explanation of how this could be a correct behavior.

**Comment by G-White-ISB** [comment]
Yeah I haven't followed the discussion well enough. Let me try an example. If we have 3 cases with CT modality only, 4 cases with PT only, and 2 cases with CT and PT modalities then filtering with 'MODALITY=CT' will produce a chart showing only CT=5 and no other modalities. Andrey you would expect the pie chart to show 5 cases with CT modality and 2 with PT modality? I guess a pie chart is confusing since the sum of the number of cases shown for each modality could be greater than the total number of cases. 
This is coming up because we are modeling after gdc and isb-cgc and in those portals I think all the attributes are exclusive - you would not have a case matching more than one.

**Comment by fedorov** [comment]
@G-White-ISB thanks for the response! I was struggling with this this morning ...

> This is coming up because we are modeling after gdc and isb-cgc and in those portals I think all the attributes are exclusive - you would not have a case matching more than one.

Right, that's probably the key, since for our data attributes are most definitely NOT exclusive, and I perhaps you nailed the source of the troubles we've been having.

> If we have 3 cases with CT modality only, 4 cases with PT only, and 2 cases with CT and PT modalities then filtering with 'MODALITY=CT' will produce a chart showing only CT=5 and no other modalities. Andrey you would expect the pie chart to show 5 cases with CT modality and 2 with PT modality?

Yes, I think that would be the logical behavior which I would be able to explain. We define a cohort based on the presence of CT modality for a given case, and then charts summarize the attributes along the dimensions we define for the selected cohort. So yes, for your example I would expect a chart showing 5 CT and 2 PT as modalities, summing up to more than 5. Explanation of such behavior would be the following:

"Show counts of cases for each of the modalities present in the cohort".

If we assume that the current behavior for the Modality is correct and should show 5 cases, then what is the explanation of what that Modality piechart shows? Also, what are we expecting the other plots to show?

**Comment by s-paquette** [comment]
After digging around a bit, I discovered the piechart situation. It's that due to the change to make 'child records' (i.e. derived data records without original data column values) was causing a sort of 're-inclusion' of the original records. I have a fix for that, so that the records are only subqueried if they have no modality (lack of modality was optional, hence the re-inclusion). So, let me get that merged in and we can see if this gets the counts to where you'd expect.

...and yes, lack of attribute exclusivity is the main issue we're going to have with counts, in general. This mostly means we need to think carefully about how we present them. Per case or per study (or even per series) will have a large impact on the counts.

**Comment by fedorov** [comment]
Please comment in https://discourse.canceridc.dev/t/understanding-idc-portal-cohort-plots/81/7?u=fedorov on the accuracy of the definition as I understand it.

**Comment by wlongabaugh** [comment]
If a pie chart was to show 5 and 2, then we are showing studies, since pie charts are by definition showing features that partition a set (i.e. are mutually exclusive and cover the set). If we are graphically showing non-exclusive attributes, then the appropriate visualization is an Euler diagram (Venn diagrams with no empty intersections shown).

**Comment by G-White-ISB** [comment]
So I'm not sure what you mean by 5 and 2 above. We actually are not
returning the right data to construct Euler diagrams - we don't return the
sizes of intersections between attributes.
George

**Comment by G-White-ISB** [comment]
'So I'm not sure what you mean by 5 and 2 above. ' - Sorry thats above of course.

**Comment by wlongabaugh** [comment]
Yes, we would need intersection counts to depict correctly. For this simple example, the selection of a filter picks a circle out of the Venn diagram, and all cases within the circle are chosen. If you pick another filter, another circle is selected, and all cases in that circle are added to the cohort.
![VennFilter](https://user-images.githubusercontent.com/8441547/92291383-3f8af880-eecd-11ea-9a0b-2b2ec19d57aa.png)

**Comment by wlongabaugh** [comment]
So a bar chart that broke out all the unique set membership combinations could do the same thing, and is highly scalable. 
<img width="530" alt="ModalityBar" src="https://user-images.githubusercontent.com/8441547/92291809-27b47400-eecf-11ea-9c08-77d4e9094793.png">

**Comment by wlongabaugh** [comment]
BioFabric Plot as an Euler Diagram. Use bar height instead of width for cardinality of subset, use the Gray code ordering of the set intersections as shown here (only one element changes between adjacent subsets), and away you go. 
![BioFabEuler](https://user-images.githubusercontent.com/8441547/92292144-89c1a900-eed0-11ea-92b5-030840a2d925.jpeg)

**Comment by wlongabaugh** [comment]
We might need a log scale on the bar chart to handle the large dynamic range between tiny intersections and large size of one-modality-only cases.

**Comment by wlongabaugh** [comment]
Clicking on a bar labeled as a set intersection would toggle all the filters tied to that set intersection.

**Comment by wlongabaugh** [comment]
So say we have four modalities, and there are cases with each combination of the four. Here is what I will dub an EulerBar depiction, with modality MR selected. Note that some modalities are not contiguous regions; in this plot, CT and MR are contiguous, the other two are not.

[EulerBar.xlsx](https://github.com/ImagingDataCommons/IDC-WebApp/files/5177383/EulerBar.xlsx)

**Comment by wlongabaugh** [comment]
If we wanted to be visually explicit about the existence or absence of overlapping attributes in the filter set, we could switch between pie charts and EulerBars depending on whether all set intersections were null or not.

**Comment by wlongabaugh** [comment]
Of course, if we are creating pie slices for all the non-null combination subsets and labeling them as such, we can go back to using a pie chart, since those partition the set.

**Comment by G-White-ISB** [comment]
Testing needed (dev.090920201037.46fd5a). None attribute filters are disabled in the 'derived' tab with a tooltip trying to explain why. I am open to suggests on the tooltip text. I realize now the tooltip should activate when user is hovering over the word None and not just the checkbox.

**Comment by madelyngreyes** [comment]
I agree with George the tool-tip should activate over the text as well. 

The text looks good to me. 
<img width="202" alt="none description" src="https://user-images.githubusercontent.com/16824894/92790035-68056d80-f379-11ea-8738-cd93e09b88f7.PNG">
Does this work for you as well by chance? @fedorov

**Comment by fedorov** [comment]
Yes, the current behavior is fine with me. Thanks.
