### ISSUE TITLE
Update front page links to open specific series

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#311]
@s-paquette would it be very difficult to update the URLs to add the following suffixes to select the specific series we show in the thumbnails?

CT: `/?seriesInstanceUID=1.2.276.0.7230010.3.1.3.0.57823.1553343864.578877,1.3.6.1.4.1.14519.5.2.1.6279.6001.273525289046256012743471155680`
MR: `/?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.1706.4001.315980779833795710131738723922`
PET: `/?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.2744.7002.746890305525203600008140092112,1.3.6.1.4.1.14519.5.2.1.2744.7002.304930022156956249911027532702`

**Comment by wlongabaugh** [comment]
So the viewer in dev and test can now handle these URLs, so we can add them right now. The suffixes above glue directly onto the existing URLs, e.g. the existing DICOM ID stays in the URL, with the /?seriesInstanceUID= glued on. I see that the existing URLs (e.g. search '1.3.6.1.4.1.14519.5.2.1.6279.6001.224985459390356936417021464571') show up in IDC-WebApp/idc/views.py and in IDC-WebApp/templates/idc/landing.html. Not sure where I see the tooltips specified in views.py showing up? I figure that @mitianisb can do this instead of @s-paquette. Ideally, long-term these should be specified in the env file, a config file, or DB table.

**Comment by mitianisb** [comment]
@wlongabaugh I have updated the links. It is in a PR with some other ticket's changes. I can also change them to be from env file after MVP.

**Comment by wlongabaugh** [comment]
Thanks!

Bill
