### ISSUE TITLE
Add cohort 'data version' display to UI for cohort details

### ISSUE THREAD

**Issue by s-paquette** [ImagingDataCommons/IDC-WebApp#373]
Cohorts are versioned by the version of IDC at the time they're saved. This should be clear in the cohort details UI and on the cohort list page.

**Comment by mitianisb** [comment]
@s-paquette One clarifying question: does this mean the version like below? I noticed it is following the website's data version instead of the cohort saved data version. Is the ticket asking to fix that, and also add a new column in cohort list to show the version it was saved with?
![image](https://user-images.githubusercontent.com/58752821/95419799-2a9bed80-08ef-11eb-99f8-3d5a63bc6f73.png)

Thanks!

**Comment by madelyngreyes** [comment]
![data portal version present on the test tier](https://user-images.githubusercontent.com/16824894/96321175-72530100-0fe2-11eb-8300-57a2b4191dec.PNG)
