### ISSUE TITLE
Filters_for_load argument is not used

### ISSUE THREAD

**Issue by G-White-ISB** [ImagingDataCommons/IDC-WebApp#384]
Filters_for_load does not appear to preload filters on the explore page. Also applying this argument should result in the explore page appearing with the appropriate filters prechecked, and the save cohort option enabled.

**Comment by s-paquette** [comment]
Okay, this was a small constellation of items:

- It takes too long for all of our JS to load, so we can't use window.onload reliably. Swapped to it being an inline script call.
- attrId became filter-attr-id but the save_anonymous_filters method got missed in the refactor
- Issues with .prop() vs. .attr() and button vs. anchor for the save/login button, as well as use of an onclick prop instead of a jQuery handler, was causing inconsistent behavior in the Log In To Save functionality.
