### ISSUE TITLE
Search scope panel collections count for tcga is zero when certain filters are selected

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#413]
On the Explore Image Data page if you have selected the attribute gender: female from the Related tab then select the collection lidc_idri with the attribute segmentation category: Morphological Abnormal Structure, the collection tcga count is represented as zero.

![2020-10-16 (12)](https://user-images.githubusercontent.com/16824894/96322297-84cf3980-0fe6-11eb-8de4-bd07c2868e4b.png)

**Comment by s-paquette** [comment]
This isn't really a bug. You specified a Derived filter, and derived filters aren't available in any TCGA collections at the moment. Unlike related filters, which are ONLY applied to TCGA collections, Derived filters are applied to ALL collections. Since nothing in TCGA has derived values, this will automatically cause them to fall out.

**Comment by s-paquette** [comment]
Note, if we want Derived filters to *only* apple to collections with derived data, we can do that, but at the moment this is not how things are set up.
