### ISSUE TITLE
Add a link on collections page that allow user to download a manifest of entire collection

### ISSUE THREAD

**Issue by mitianisb** [ImagingDataCommons/IDC-WebApp#429]
User request: Have a link on the Collections page that allows you to download a manifest of the entire collection (clearly needs the BiqQuery and/or multi-click workaround for > 32 MB). Note we could also have permanent manifests for each collection in BQ tables.

**Comment by mitianisb** [comment]
We had a discussion about this ticket in the ISB team's meeting. To make this work we need to make some changes first:
1. We still want to require log in first before user can download. We could show download button in the collection table, and it will ask user to log in. If user already logged in, it can download directly.
2. Right now manifest can only download from a cohort. We need to make download manifest work without cohort creation to support this ticket.
3. Entire collection manifest is very large, so we need to support download using BQ or multi-chunk file download. #394

**Comment by s-paquette** [comment]
Actually this is the ticket which collides with our current plans, so we'll want to close it.

1) We require users to log in before downloading the manifest this because we don't want bots hitting the site and running up large egress charges. We have no plans to make downloading absent of a login available, (unless we want to keep the size limit in place when a user isn't logged in).
2) Ticket #404 (referenced above) is the actual solution; the user will go to the explorer page with the collection selected, then can save the collection and download the manifest.

So, for the moment, I'm going to backlog this ticket, and we can consider it in the future. For now, it conflicts with our priorities to prevent the site from overrunning the budget.

**Comment by fedorov** [comment]
Why can't we just have a very simple BQ query that would select all items in the collection?

**Comment by fedorov** [comment]
![image](https://user-images.githubusercontent.com/313942/142968479-8d55c9d5-c3e5-4e74-a0ae-38ed14fde945.png)

Is this still "wontfix" or not?

**Comment by s-paquette** [comment]
Since we now have the ability to get a BQ query without logging in or making a cohort, this is effectively solved.
