### ISSUE TITLE
Update download manifest dialog to support fetching very large manifest (multi-chunk download, BQ, etc.)

### ISSUE THREAD

**Issue by mitianisb** [ImagingDataCommons/IDC-WebApp#432]
This is the front end work needed to support very large manifest file download. 

Related to #394

**Comment by mitianisb** [comment]
![image](https://user-images.githubusercontent.com/58752821/99219585-d4458880-2791-11eb-98cd-0965c8596e28.png)

**Comment by mitianisb** [comment]
@s-paquette I did a mock-up for updating the download manifest dialog to support muti-chunk and BigQuery download. Please let me know your thought. 
![manifestUI](https://user-images.githubusercontent.com/58752821/99298363-74d19200-27fe-11eb-8b62-8074dbbaa2ed.gif)

**Comment by s-paquette** [comment]
This looks great to me! @fedorov Any changes desired?

**Comment by fedorov** [comment]
Looks good to me! Just a few thoughts:
* can you add some note about how those chunks should be collated together? Are these separate manifests with headers that added together correspond to the complete manifest? Or should those files be concatenated?
* we should have the name of the file to be something more informative, maybe something like "IDC_cohort-<name>-<date>".
* what happens after selecting BQ and clicking "Get BQ Table"?

**Comment by mitianisb** [comment]
Thanks for the feedback @fedorov! This is only a fake mock-up now and I will make it work with the backend Suzanne will implement later. @s-paquette please correct me if any of my following answers are wrong:

1. I think they will be separate manifest files downloaded to the user's computer. And the user will combine them by themselves. @s-paquette Maybe we can have an option to make the files after part 1 only have the data rows, so they can be appended to the last file more easily?
2. Good idea, they can also be based on the name user typed at the top, like MyCohort_Date_Time_Part1.
3. My understanding is this will return a link to the BQ table contain the manifest data.

**Comment by fedorov** [comment]
> My understanding is this will return a link to the BQ table contain the manifest data.

Will that be a public dataset, or one that is available to the user only?

Did you consider creating a public or shared view instead of a separate table? If we could do the view, then we would not need to worry at all about the storage costs, and potentially could keep that view around forever and linked to the user cohort.

**Comment by s-paquette** [comment]
@fedorov Unfortunately we can't use a view because the user then requires direct access to the underlying table. The storage costs for BQ are minimal, especially over the course of a week, which is our proposed expiration time for the table. The dataset and table will not be public, they'll be limited to the user's Google account (so the BQ option is only available to users with a Social Account attached, but they have to have a Google account to make use of BigQuery anyways).

**Comment by fedorov** [comment]
> Unfortunately we can't use a view because the user then requires direct access to the underlying table.

I don't understand this. Quoting from https://cloud.google.com/bigquery/docs/share-access-views: "An authorized view lets you share query results with particular users and groups **without giving them access to the underlying tables**."

**Comment by s-paquette** [comment]
@fedorov Per the description, the user is still placed onto the dataset with a role, which we really don't want to do (curate individual user access to our data project). By making them a temporarily lived table which can be accessed at their leisure, we don't need to do much after we export it--it'll go away after a week.

**Comment by fedorov** [comment]
As discussed, it is difficult for many reasons to maintain authorized views, mostly due to security related considerations. We will not explore this direction.

**Comment by mitianisb** [comment]
This is the current look for the manifest dialog.

![Screen Shot 2020-11-30 at 7 49 50 AM](https://user-images.githubusercontent.com/58752821/100631538-ae1aff00-32e0-11eb-8383-461dc34249be.png)

**Comment by mitianisb** [comment]
@fedorov @madelyngreyes There are a few notes that I think would be worth mentioning for this dialog:
1. JSON file does not include header field, they only apply to CSV and TSV files. This is because to make JSON file upload to GCP BQ table Google require a certain JSON format without the option to skip headers.
2. The file part select box is hidden when the manifest is less than 65000 (only one file needs to download).
3. The download file name has a file part number in it, such as "MyCohort_20201130_74710_Part2.csv". This way it is easier for the user to track which part has already been downloaded.

**Comment by fedorov** [comment]
I have couple of questions re BQ export:
* would it be possible to add a link to the BQ table corresponding to the exported cohort to the cohorts table somewhere? 
* it looks like all of the user-exported cohorts are visible to everyone - I am not sure this is a good idea. I can easily see how users would want to keep their cohorts private. How difficult would it be to do that?

In the below, only one cohort is the one exported by me:
![image](https://user-images.githubusercontent.com/313942/100825235-98fbb880-3425-11eb-8ccc-d7b53f4aaea1.png)

**Comment by s-paquette** [comment]
@fedorov 

> would it be possible to add a link to the BQ table corresponding to the exported cohort to the cohorts table somewhere?

Because these exported tables only exist for 7 days, that wouldn't really work. Their names change on subsequent exports due to timestamps in the table name.

> it looks like all of the user-exported cohorts are visible to everyone - I am not sure this is a good idea. I can easily see how users would want to keep their cohorts private. How difficult would it be to do that?

You're seeing this in all likelihood because the account you're using is already on the idc-dev project in some capacity (Editor, for example). In order to mimic the user experience, you'll need to use a gmail account of yours which is fully separate from IDC infrastructure. Otherwise, when you hit BQ, your account's inherited roles let you see all the tables. One of the other tickets, ImagingDataCommons/#394, has comments to this effect (and a few questions about other things

**Comment by fedorov** [comment]
> Because these exported tables only exist for 7 days, that wouldn't really work. 

Would it work to keep track of the past exports, and if the table is still around, provide the link to that table in the cohorts list?

A problem with the current approach is that the link to the exported cohort is very easy to miss, and impossible to recover. Cohorts table is the most logical place to for that link to stick around.

**Comment by s-paquette** [comment]
> Would it work to keep track of the past exports, and if the table is still around, provide the link to that table in the cohorts list?

We could do this as an enhancement, but that would be a significant level of work added. Definitely not something for this sprint.

**Comment by madelyngreyes** [comment]
Error returned when trying to export a large cohort to BigQuery.
![error from test tier](https://user-images.githubusercontent.com/16824894/101060691-afa52b00-355d-11eb-9826-9735134f9d47.PNG)

**Comment by madelyngreyes** [comment]
For tracking, when using a large cohort the export to CSV will return multiple errors when the end user attempts to download file # 47 without loading any of the previous options first. 

![2020-12-03](https://user-images.githubusercontent.com/16824894/101063413-c436f280-3560-11eb-8863-9371acecf632.png)

**Comment by s-paquette** [comment]
Regarding large file chunks. Having done some research on it, this is a known limitation with search indexers like Solr. For this Sprint, I suggest we limit downloadable files to about 10 chunks maximum, and otherwise users must have a Google Account and export to BQ or obtain a query to run against the Pivot table.

Going forward there are some options to allow 'deep paging' (i.e. walking through a very large set of paginated results from a Solr query) but they're a bit complicated and as we've discussed elsewhere it may not be something users would care about.

**Comment by mitianisb** [comment]
This is the current look for the large manifest download.
<img width="634" alt="Screen Shot 2020-12-04 at 4 54 41 PM" src="https://user-images.githubusercontent.com/58752821/101228745-df355f80-3651-11eb-9e40-29ea921b3a83.png">

**Comment by madelyngreyes** [comment]
From earlier today, 
![error returned on the test tier](https://user-images.githubusercontent.com/16824894/101383710-79321d80-3887-11eb-940b-0f90c99c789d.PNG)
