### ISSUE TITLE
Questions related to manifest info in BigQuery tables

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#490]
- Do you have an estimate of how long it takes to create the BQ tables e.g. per 100,000 instances?
- Is there a message when the transfer has been completed? I am still seeing this message and I am not sure if the job has been completed?
![image](https://user-images.githubusercontent.com/3019001/102122782-fe7f7a00-3e13-11eb-9b8e-f8e32c65c483.png)

**Comment by fedorov** [comment]
> Do you have an estimate of how long it takes to create the BQ tables e.g. per 100,000 instances?
> Is there a message when the transfer has been completed?

No, we don't. We have been brainstorming different approaches how to improve usability here. One idea is to keep links to the exported BQ tables in the cohorts list. We could also include the status of export at the time user opens the cohorts list. Would that address your concern?

**Comment by s-paquette** [comment]
@ulrikew Would Andrey's suggested changes address this? We have it on our radar to come up with a way to track prior exports and if they're still available provide a link from the cohort list page. (As the tables time out after 7 days we need to come up with a cleanup mechanism, so we're still brainstorming.)

**Comment by ulrikew** [comment]
Yes, that would be helpful.

**Comment by s-paquette** [comment]
@wlongabaugh @fedorov I think I've come up with a way to do this without a cron job.

Since this is user-centric information, i.e. something only the user can access, we don't need a cron job, we just need to check when they load their cohort list. If the export date is >= to 7 days, we check to see if the table is still there, and if not we remove the entry. This should be a fairly lightweight just-in-time check since users are unlikely to be exporting that many manifests at a time.

If you think this is workable I can slate this for Release 28.

**Comment by fedorov** [comment]
Sounds helpful to me.

**Comment by s-paquette** [comment]
@ulrikew This is now available on the IDC test tier.
