### ISSUE TITLE
Inconsistent number of items in the cohort between portal and direct BQ query

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#507]
The total number of rows in our public view is 3075233.
```
SELECT count(SOPInstanceUID) FROM `canceridc-data.idc_views.dicom_all`
```

If I select all of the collections in IDC portal, and export the resulting cohort into BQ, I get 2017036 rows.
```
SELECT count(SOPInstanceUID) FROM `canceridc-user-data.user_manifests.manifest_cohort_82_20201222_194659`
```

The underlying query for the above is just selecting all of the collections, and does not touch any other attributes.

![image](https://user-images.githubusercontent.com/313942/102944687-7fc8b380-4489-11eb-87df-87105f996a0c.png)

**Comment by fedorov** [comment]
Related to #182 (since we don't have any way to get to a BQ query matching the cohort), and to #377 (since this raises the urgency of being able to cross-check the cohort content defined against Solr with direct BQ queries).

**Comment by s-paquette** [comment]
Okay, got this sorted out for exports. Issue was twofold:
- 'program name' is being used as a filter even though we don't offer it to the user
- 'related' tables were being joined without LEFT join

JOINs made against anything from a 'related' set will now be done as LEFT and will require a non-null 'count column' in order to qualify for filter application (the column we count by is typically a case or study ID and thus would never be null unless a record isn't present in the table, in which case, we don't *want* it to be filtered for the purposes of related data).

**Comment by madelyngreyes** [comment]
Ran same test as Andrey and returned the correct count on the test tier. 
![results to test run](https://user-images.githubusercontent.com/16824894/104040875-32955300-51a6-11eb-8ae0-cbd58f2da1ef.PNG)


Will next check for counts returned when using filters from the original, derived, and related tab.

**Comment by madelyngreyes** [comment]
Working draft test notebook created, https://colab.research.google.com/drive/1xvbUiGtJJWT9jZgcrC26iksakDLvLT7a#scrollTo=ABSABsu5wg-4
