### ISSUE TITLE
How does a user know which series belongs to what study?

### ISSUE THREAD

**Issue by ulrikew** [ImagingDataCommons/IDC-WebApp#526]
When a user selects multiple studies how does the user know which series belongs to what study?
The same is true for cases to studies.

![image](https://user-images.githubusercontent.com/3019001/104637132-5fe47400-5672-11eb-8e2e-be8decfe5a22.png)

**Comment by s-paquette** [comment]
@ulrikew The study a given series belongs to is listed in the left-most column (abbreviated for size, though the last 12 digits are visible to allow for differentiation).

**Comment by fedorov** [comment]
@ulrikew we have several ideas about how this could potentially be addressed, but I am reluctant to prioritize this because I do not see a use case where this could be important. In 3D Slicer we have a similar interface, and we never had requests of similar kind to trace back series to studies. I suggest we revisit this if we get similar user requests in the future.

**Comment by ulrikew** [comment]
Ok, sounds good. Thank you, Suzanne and Andrey for your comments.
