### ISSUE TITLE
Black screen while browsing

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#59]
I am not sure how to reproduce this, but while testing the portal, I got to this error:

![image](https://user-images.githubusercontent.com/313942/76801896-f030fe80-67ac-11ea-9c89-b7d4acd1502c.png)

**Comment by fedorov** [comment]
@pieper FYI

**Comment by fedorov** [comment]
Hopefully this is resolved by the update to the most recent version. Let's keep the issue open for a while in case anyone else encounters similar problem.

**Comment by madelyngreyes** [comment]
I was able to reproduce the black box issue as well. I have created a short video to display the error. 

![black box while selecting filters in IDC](https://user-images.githubusercontent.com/16824894/80725917-b6545700-8ad1-11ea-8bca-a4dec6568a81.gif)

**Comment by fedorov** [comment]
@madelyngreyes can you clarify what the issue is and the status in current testing?

**Comment by madelyngreyes** [comment]
I see a load time grey box appears that doesn't cover the entire screen while highlighting a Selected Studies option. This issue seems to be present in the test tier. 

I think I could be referring to a different black screen while browsing than the one you originally mentioned. I have listed the steps to reproduce the issue below. 
1. Select body part examined from the Search Results panel
2. Select the option tcga_gbm in the Collections panel
3. Scroll down 
3. Select the option case Id TCGA-CS-4941 in the Select Studies panel 
4.  A black screen only covers half the page

I also attached a short video.
![test tier half grey box appears](https://user-images.githubusercontent.com/16824894/87999655-89f51900-cac9-11ea-91cc-109c3e2bacb3.gif)

**Comment by fedorov** [comment]
Indeed, it's a different issue. @G-White-ISB is this grey box expected behavior?

**Comment by fedorov** [comment]
@wlongabaugh says the gray area must cover everything

**Comment by G-White-ISB** [comment]
Fixed in next PR

**Comment by fedorov** [comment]
This appears to be fixed.
