### ISSUE TITLE
Derived filters are not handled properly for export to BQ (download is fine)

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#617]
![image](https://user-images.githubusercontent.com/313942/117848425-4be00600-b251-11eb-9913-6a7f74bd6177.png)

**Comment by s-paquette** [comment]
Okay, I know what the issue is here. The issue is, there's no such cohort, actually. The reason is a bit more complex.

When setting up the new Solr indicies, I forgot that there's the notion of each instance within a series having different data values, when it comes to derived data. Which is to say, in Study 1, Series A, you maybe have Instances 00 and 01. 00 might have Volume NULL but Nodule for a Segmentation Type. 01 Might have a different Segmentation Type but the Volume you requested. If you aggregate all instance data together for a study, it LOOKS like you have a single instance with those 2 values, but you don't. BigQuery of course catches this because it's a full instance-level table.

I'll need to see if I can come up with a way to structure the index to allow for this kind of specification of instance-grouped values.

**Comment by s-paquette** [comment]
@fedorov @wlongabaugh @bcli4d This does bring up a thorny issue, though--the notion of 'study level' attributes vs. 'series level' vs. 'instance level'. For example, are there attributes with values which are the same for all instances in a study, because it's effectively a trait of the study, and not the instances? (I'm thinking Body Part Examined.)

**Comment by s-paquette** [comment]
Sidebar, maybe we DO want to let people search for series/studies with 'instances which have one OR the other of these values, at least one of each' vs. series/studies with 'instances which have BOTH values'. At any rate, I've looked up how to do the child-doc setup, not sure on how big such a core would be but we'll find out once I get it running.

**Comment by fedorov** [comment]
We discussed this today, @s-paquette will summarize next steps here.

**Comment by s-paquette** [comment]
The issue here has to do with how derived data is managed in the BigQuery tables. Unlike in Solr, where records are collapsed to the Series or Study level, in BigQuery all records are instance level. A given instance will typically not have all values for attributes from a series' derived records; they will spread over the instances. In order for the derived filters to properly AND between themselves, an intersection of the derived filters must be done to ensure ALL of the values are present in the given series' instance records. (A simple OR will only guarantee 1, a full AND will always fail.)

**Comment by G-White-ISB** [comment]
Related to[ 641](https://github.com/ImagingDataCommons/IDC-WebApp/issues/641). Maybe a duplicate

**Comment by s-paquette** [comment]
@G-White-ISB Not a duplicate. This issue is explicitly related to a back-end issue regarding how derived filters are handled.
