### ISSUE TITLE
selection of collection CT Colonography (ACRIN 6664) doesn't open the selected series related to cases selected

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#626]
On the test tier, from the exploration page if you select the collection CT Colonography (ACRIN 6664), then cases the selected studies panel doesn't populate with options for selection. 

https://user-images.githubusercontent.com/16824894/118200417-fd826100-b422-11eb-8cca-a0f5d583d1cb.mov

**Comment by madelyngreyes** [comment]
This ticket is still broken on the test tier. No data is present in the selected studies panel.


Uploading Screen Recording 2021-06-09 at 4.56.22 PM.mov…

**Comment by G-White-ISB** [comment]
Also fails on dev. It seems to be particular this collection. I just did a spot check of 6 other collections on dev and this issue did not come up

**Comment by G-White-ISB** [comment]
CT Colonography (ACRIN 6664) studies and series open fine in the local environment

**Comment by fedorov** [comment]
I confirm this remains the issue.

**Comment by s-paquette** [comment]
I can't replicate this on production. @fedorov @pgundluru @madelyngreyes If this is still replicable can you give us exact steps, the whole way through, that you made it happen?

**Comment by G-White-ISB** [comment]
Select the collection 'CT Colonography (ACRIN 6664)', in the 'Collections' table. The 'Selected Cases' table is populated with the relevant cases. Then select any case. The relevant studies do not show up in the 'Selected Studies' table. As of this morning (June 18) I see this in the production, test, dev, and local environments. Last week I reported that I did not observe this behavior in the local environment. My tests are done on a Mac using both Chrome and Safari.
<img width="1334" alt="Acrin" src="https://user-images.githubusercontent.com/58443591/122583272-e6302800-d00d-11eb-8519-5dcfb7b403fa.png">

**Comment by s-paquette** [comment]
@G-White-ISB  This is an issue with how the front end is treating case values. The intermittent nature is due to it being a JS problem, and sometimes we're getting cached JS. This is only a problem with collections where the cases have `.` in them.  For some reason, they're being converted prior to storage as values in the table display, exchanging the `.` for a `-`. This is then sent back in a filter:

`{'collection_id': ['ct_colonography'], 'PatientID': ['1-3-6-1-4-1-9328-50-4-0003']}`

Which obviously doesn't match the actual case ID, this it fails to find anything. Not sure where this replacement is happening, but values themselves should never be altered in any way (just displayed values). The initial call which sends back the case IDs definitely is returning them correcntly:

`{'val': '1.3.6.1.4.1.9328.50.4.0785', 'count': 1, 'unique_count': 4}`

I don't see the backend doing any replacements:

![image](https://user-images.githubusercontent.com/8442808/123651764-9ce79180-d7e0-11eb-966c-8c6bde0fd7e2.png)

So this is happening on the front end somewhere.

**Comment by G-White-ISB** [comment]
I was storing the PatientIDs, SeriesUIDS, and StudyUIDS with '.' replaced with '-'.  I honestly have forgotten why now. I think I had some JS where the '.' was being interpreted as denoting an object. StudyUIDs and SeriesUIDs were being reset before the call but not PatientIDs. Anyhow I'll take out this conversion and test that everything works.
