### ISSUE TITLE
Update Primary site locations to correspond to TCIA values

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#634]
TCIA updated the values for the primary site recently. As an example, there is no longer "Head-and-Neck", only "Head-Neck". We should update the values in IDC to match TCIA, definitely before pushing test to production.

**Comment by s-paquette** [comment]
Note, I did go through and do the data update, so we should now be up to date with TCIA per the v2 data release updates BillC did last week. We still have the other ticket which is regarding count mismatch in the TCIA table vs. the DICOM ETL. @bcli4d @fedorov How would this need to be tested by @madelyngreyes and @pgundluru ?

**Comment by madelyngreyes** [comment]
waiting on feedback for testing needed

**Comment by fedorov** [comment]
The other ticket is #625. To test you could selectively or exhaustively select one collection at a time from the IDC portal, and compare the primary sites corresponding to that collection in IDC portal with the values of primary sites for that collection in this table: https://www.cancerimagingarchive.net/collections/.

**Comment by bcli4d** [comment]
As I described in  #625, I compared distinct case counts per collection in dicom_all with Subjects in original_data_collections and found 16 cases where counts differ. I verified that our counts match the counts on the TCIA Radiology exploration page counts except for one collection for which additional cases have been added since we downloaded.
