### ISSUE TITLE
Modality count on BigQuery table doesn't match the exploration page

### ISSUE THREAD

**Issue by madelyngreyes** [ImagingDataCommons/IDC-WebApp#666]
Checking the modality options available for a cohort with all collections exported to BigQuery it said only 25 filter options are present when using the query 
SELECT

DISTINCT(modality)

From `idc-testing.test_user_dataset.manifest_cohort_184_20210614_211243` AS my_cohort

JOIN

`canceridc-data.idc_views.dicom_all` AS all_data

ON

my_cohort.SOPInstanceUID = all_data.SOPInstanceUID

But, on the exploration page there are 23 filter options present. 

<img width="469" alt="Screen Shot 2021-06-14 at 5 15 51 PM" src="https://user-images.githubusercontent.com/16824894/121960805-995e0000-cd34-11eb-8502-d24ca60c806a.png">

<img width="663" alt="Screen Shot 2021-06-14 at 5 18 50 PM" src="https://user-images.githubusercontent.com/16824894/121960948-c6aaae00-cd34-11eb-9e58-807d9f239b36.png">

**Comment by s-paquette** [comment]
@madelyngreyes @pgundluru A note that since exported manifests time out after 3 days, it's best to not use those in bug reports. Better to copy them into another project where they can be stored, after export, so devs can have access to them.

If you could re-export this cohort and then copy the resulting table into a new project, we can get a better look at this one. Note though that the number of values offered on the site includes `None` so that has to be removed from the calculations.

**Comment by s-paquette** [comment]
@madelyngreyes @pgundluru Added note--idc_views.dicom_all is a v1 view at the moment, but this cohort appears to be v2. The difference in counts is expected in this case. It means the view should be updated to point at v2 if it is indeed intended to be a 'current' view. @bcli4d @fedorov

**Comment by fedorov** [comment]
Nice catch! 

@s-paquette the organization of BQ views in v2 is different from what we had in v1. Views are no longer in a separate `idc_views` dataset, but are directly under the `idc_v2` dataset. So `dicom_all` is here: `canceridc-data:idc_v2.dicom_all`. You can see the locations of all tables and views documented in https://learn.canceridc.dev/data/organization-of-data/files-and-metadata#bigquery-tables.

**Comment by s-paquette** [comment]
Going to close this one out.
