### ISSUE TITLE
Additional top-level pages to be discussed

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#668]
Per discussion with @ulrikew, Ulli and Keyvan would like to see a top-level "About" page discussing what IDC is and what is the submission process (in addition to the "News" page, which is already captured in another ticket).

My personal preference would be to at least consider linking FAQ from the front page, and keep all those questions covered there (and also link Discourse "Announcements" section for maintaining News).

**Comment by s-paquette** [comment]
If I'm given 'About' page content it's easy enough to make a page for it.

I'm not sure where the FAQ is but if I'm given a link that's easy enough to link.

**Comment by fedorov** [comment]
In order to support embedded Discourse widget enabled the following

![image](https://user-images.githubusercontent.com/313942/124638374-e11a0800-de58-11eb-8814-59fc49d38e1c.png)

**Comment by fedorov** [comment]
@s-paquette I discussed the plan to use discord widget/ticker for displaying the latest posts from the Announcements category with @ulrikew, and she liked the idea. Would be great if you could share the mockup whenever you have it, before you go into the implementation.

**Comment by s-paquette** [comment]
@fedorov I have it on dev at the moment, since the implementation itself is very simple. The basic theme (so this is, in effect, the mockup):

![image](https://user-images.githubusercontent.com/8442808/128668322-57585608-15dc-4ca1-abe4-1c74a40c65d7.png)

Note the icons in use for News and About, as well as the placement; easy enough to change, just look through the [Font Awesome Free set](https://fontawesome.com/v5.15/icons?d=gallery&s=regular,solid&m=free) and let me know if you'd prefer something else. 

Changes to the theme need to be written on Discourse proper, by I believe an admin (I don't seem to have access to the Discourse Theme section which would be where this is done).

**Comment by s-paquette** [comment]
@fedorov Note I also need content for the about page as well. It's just a stub at the moment.

**Comment by ulrikew** [comment]
Thank you, Suzanne and Andrey. I will forward the screenshot to Keyvan to get his feedback and to remind him that we need content for the About page.

**Comment by fedorov** [comment]
Thanks Suzanne. I've just granted you the admin access on discourse.

I suggest this icon for the "About" section:  https://fontawesome.com/v5.15/icons/info-circle?style=solid

**Comment by s-paquette** [comment]
@fedorov Thank you! @ulrikew The good news is adjustments to this CSS are done on Discourse itself which means they can be implemented without redeploying the site.

Icon changed out.

**Comment by fedorov** [comment]
@s-paquette do you think it makes sense to add an opening to this page that says something like the following:

"The list of posts below is populated automatically from the ["Announcements" category](https://discourse.canceridc.dev/c/announcements/5) of the [IDC Discourse forum](https://discourse.canceridc.dev/)".

Regarding the styling, would it be possible to modify the CSS to exclude embedding of the logos in the posts? That big green SPL logo looks out of place to me, and does not add anything helpful.

**Comment by s-paquette** [comment]
@fedorov @ulrikew  Unfortunately hiding the logo might require more than a minor CSS tweak. I'd like to ask we make a new ticket for those kinds of adjustments, rather than hold this one open. It will need to be done next release as this release is already having trouble getting its current workload done. 

I don't have copy for the About page yet, so it remains a stub. Otherwise, this now on test.

**Comment by fedorov** [comment]
Let's use the below for the About page text:

---

**About IDC**
 
The National Cancer Institute (NCI) [Cancer Research Data Commons (CRDC)](https://datacommons.cancer.gov/) aims to establish a national cloud-based data science infrastructure. Imaging Data Commons (IDC) is a new data repository of CRDC supported by the Cancer Moonshot. The goal of IDC is to enable a broad spectrum of cancer researchers, with and without imaging expertise, to easily access and explore the value of de-identified imaging data and to support integrated analyses with non-imaging data utilizing CRDC Cloud Resources.
 
**Data Submission to IDC**
 
IDC only hosts public datasets.  It does not support access limitations, such as, data embargoes or sequestration.
 
Submitters of data to IDC must ensure that the data have been de-identified with respect to protected health information (PHI).  Currently, IDC accepts data de-identified by [The Cancer Imaging Archive (TCIA)](https://www.cancerimagingarchive.net/).  Datasets de-identified by other data coordinating centers (DCC) may be considered but in such cases further information will be required.
 
If you are interested in making your data available within IDC, please contact us by sending email to support@canceridc.dev.

**Comment by s-paquette** [comment]
@fedorov Done and on dev and test.
