### ISSUE TITLE
In the exploration page, when you add a collection or check all for collections and filters while logged out and then log in the filters are not saved 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#670]
**General description:** 

In the production tier of IDC, When i select all the filters in the collections section while logged out of the IDC page and then log back in i don't see any of the previously selected filters.

**Steps to reproduce the behavior:**
 - IOS: W10
 - Browser: chrome
 1.  Go to https://portal.imaging.datacommons.cancer.gov/explore/ (not logged in)
 2. Select all filters for collections 
 3. Then log in 
 4. The previously selected filters are lost

**Screenshots**
![image](https://user-images.githubusercontent.com/85526819/122415398-e1a83880-cf55-11eb-91e8-fd3039b0d9f0.png)
![image](https://user-images.githubusercontent.com/85526819/122415610-10beaa00-cf56-11eb-9465-d5d42aa1239d.png)

**Comment by s-paquette** [comment]
@G-White-ISB @madelyngreyes @pgundluru So, the issue here has to do with the login redirect. That's done as a GET request. As previously mentioned, we switched to POST to deal with these very long URIs.

The thing is, the redirect after login can't do that. It's assumed that should be a GET. @G-White-ISB The way this should be addressed is we move to doing this how CGC does. In the case of CGC, when a user indicates they'll be logging in, their filter set is saved to sessionStorage with a key using their user ID and the login time. That variable easily fits in the redirect URI. At that point you can pull out an arbitrarily large filter set; part of the page load checks for a user being logged in and a filter set, and when it finds one it loads that filter set.

**Comment by s-paquette** [comment]
Hotfixed in production, also merged into dev.
