### ISSUE TITLE
Should include data version in the exported manifest

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#712]
Manifests for the cohorts created for earlier versions will need to be joined with the metadata corresponding to the data for the specific version using which the cohort was created, however the exported manifest currently does not indicate what version was used, and so that join operation would be error-prone (the user would need to keep track separately about which version of IDC data corresponds to the manifest exported).

**Comment by fedorov** [comment]
Can we consider including version as a column of the manifest in addition to header? I worry that having it in the header and description of the BQ table makes it easy to miss or lose.

**Comment by s-paquette** [comment]
@federov There's a bit more involved in adding it as a column as opposed to just the header (due to how BQ table schemas work). I'm leery of making that a production item as opposed to just the header for now.

We can make a new ticket which is specifically about adding it as a column which can be turned on/off like the others are slated to be, if that works? For post-production.

**Comment by fedorov** [comment]
Yes, post-production is fine.

**Comment by pgundluru** [comment]
Showing up in the header section in test tier.

**Comment by pgundluru** [comment]
This is tested in release 23 successfully
