### ISSUE TITLE
Get URL with the search filter definition

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#730]
I think it would be quite beneficial to be able to point users with a URL to specific subsets of data. For example, for the release announcement I would benefit from being able to point to the cases that have SM in the release announcement. I can probably figure it out with that excel spreadsheet, but maybe it is possible to add a button to generate the URL from the UI, if the length of the filter does not exceed some threshold.

**Comment by fedorov** [comment]
@s-paquette we are constrained by the maximum length of the URI. We in general do not exceed this length.

**Comment by fedorov** [comment]
@wlongabaugh this situation is a reminder that we really need to set up a paid Slack plan to be able to link to the Slack conversations from issues that came out of those discussions.

**Comment by s-paquette** [comment]
So, to come back to this, @fedorov I thought that in a previous discussion we had settled on a functionality which PDC has. A user can click on a button and be given a URL which will give them the same exploration page with filters loaded:

![image](https://user-images.githubusercontent.com/8442808/150586553-0f1e17c6-4f12-4a70-9d4b-b3457e09c5e6.png)

Is that a desired functionality? That seemed to be what this ticket was describing, but in the meeting today it sounded like something very different. The notion of letting users 'hand craft' a URL is somewhat uncommon in this space. They're of course welcome to try but it's not a supported idiom for a variety of reasons related to security and issues supporting backwards compatibility.

Allowing users to get the current filter set as a URL is absolutely possible (with the previously discussed length constraint, though in practice I've never seen a user make a cohort definition so complex it actually ran into this). Supporting users being able to hand-craft the URL, up to and including giving them our tables of ID mappings, is I think not supportable long term, and it's not really an expected use case outside of an API (IME) either.

**Comment by s-paquette** [comment]
Going to move this to Release 27

**Comment by s-paquette** [comment]
Should be doable with the work to support TCIA linking.

**Comment by s-paquette** [comment]
Note, the URL limit for Mozilla (Firefox) is theoretically unlimited, but for Webkit (Safari, Chrome, Edge) it's 2048 characters. We'll be going with the later for now.

**Comment by wlongabaugh** [comment]
I thought I remembered from the discussion that the key values in the URL might change over the long haul. Is this being addressed?

**Comment by fedorov** [comment]
I don't see how it would with the proposed approach (see https://github.com/ImagingDataCommons/IDC-WebApp/issues/868#issuecomment-1031925296) - the values defining the filter refer to the actual values, not internal numeric codes.

**Comment by s-paquette** [comment]
@wlongabaugh The idea here is we now have an intermediary API which takes an attribute name instead of an ID. This API then translates that into an ID. In order for this to continue working in the case of a change--say, BodyPartExamined became body_part_examined--we'd need to make a translation system to catch the old name and associate it with the new one. I've been considering a system for this, something like Attribute_Name_Resolution, which will let us store alternate names for attribute IDs. We don't have to implement it immediately, since it would only be used by this API and only when/if we have a name change. The main back-end won't be effected, as it never reveals IDs to the user and has display names, which was the real problem: giving users a table which they needed to consult and we needed to update. This frees us of that; instead, we have an API which we can more easily maintain and which continues to keep the nuts and bolts of the backend where it belongs.

**Comment by s-paquette** [comment]
URL will now flip to /explore/ if the user adjusts the filters. The filter-URL will remain on the history, so the back button allows them to re-access it.
