### ISSUE TITLE
Include version number as a column in the exported manifest

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#738]
followup on #712

**Comment by s-paquette** [comment]
This was placed as a header item instead of a column; do we really want a column? @fedorov

**Comment by fedorov** [comment]
Yes, we do. You can't do any query operations (easily) on the version in the header.

**Comment by s-paquette** [comment]
The version isn't a column in any other table, and will be the same for anything exported in the manifest. Unless this is in terms of potentially UNION'd tables?

We'll need to bump this to the next Sprint since this would be a custom column not otherwise in any of the database tables (which have instances, I mean), and that requires a different approach for adding it.

**Comment by fedorov** [comment]
My motivation for adding it is to enable archival and reuse of the manifests created using older data releases.

**Comment by s-paquette** [comment]
@fedorov This is now available on dev and test. The format is the more verbose display method; we can move to something simpler if you prefer.

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/151579157-a23c7670-cc92-4329-a414-226911004200.png)

**Comment by fedorov** [comment]
Thank you for working on this. I personally would definitely prefer to have version number in the same format as we use elsewhere - as a single number - to facilitate joins.

**Comment by s-paquette** [comment]
@fedorov @pgundluru Style has been switched to simple number-as-a-string (7.0, 6.0, etc.) and is available in dev and test.
