### ISSUE TITLE
"Select all" is missing for the tables on the right

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#741]
It would be a useful feature to be able to select all items under collections/cases/studies tables in the portal.

**Comment by G-White-ISB** [comment]
This is somewhat tricky because we need to maintain lists of which cases/studies the user has selected. With SELECT ALL these   lists could be thousands of items large. Right now the lists are stored in the browser.

Unlike pdc, gdc, or tcia we do not support downloading directly from our tables. They are only meant for the user to view metadata and of course to view images. To me this suggests we'd normally want the tables to have a 'human-friendly' length.

**Comment by fedorov** [comment]
The use case is to allow users to subset the lists based on the specific values or patterns in the column content (such as PatientID) - if you recall, this is what we discussed on Monday - adding a "search" box for the individual columns in the right-hand-side tables. If the search in that box applies only to the current page of the table, this would be of a very limited value.

**Comment by G-White-ISB** [comment]
I agree search would ONLY make sense if it's applied to the total table as defined, regardless of which page is in view, or even if the total table is loaded in the browser. That might mean a server call, so you would press a button when you are ready to search, rather a search being applied as you type in the text

**Comment by G-White-ISB** [comment]
Currently planning just to have the +/- icons that select all (or deselect all) items on current page in table. This is consistent with GDC and PDC. @fedorov if this is acceptable then we should close this issue
