### ISSUE TITLE
In production tier, When a user selects primary site location Bladder and tries to open up a series viewer, there is a 404 error. 

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#784]
This issue was observed after hotfix related to 776. 

Summary - 
In exploration page, when I select primary site location as bladder – select collection PDMR-BL0293-F563 – then select any study and select any series to display – the OHIF viewer is a blank page for the series.

Steps to reproduce:

1. In exploration page on production tier, Select primary site location as bladder 
2. Select collection PDMR-BL0293-F563 
3. Select case PDMR-BL0293-F563
3. Select any study eg BL0293-F563-40 
4. Select any series to display – the OHIF viewer is a blank page for the series.
 
Error in dev console 

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.
1.3.46.670589.11.17169.5.0.5032.2015073113554247668:1 Failed to load resource: the server responded with a status of 404 ()

Example UID - https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.46.670589.11.17169.5.0.5032.2015073113554247668?SeriesInstanceUID=1.3.46.670589.11.17169.5.0.1768.2015073114035894817.1 

**Your System**
 - OS: W10, Mac chrome

**Comment by bcli4d** [comment]
This study/series has a single instance, SOPInstanceUID=1.3.46.670589.11.17169.5.24.5.1.1768.2015073114035894817.
That instance seems to be corrupted. The corresponding file in GCS is gs://idc-open/084992f7-0d21-423b-ad93-58d930216e9c.dcm, and is identical to the instance in DICOM store.
I am pretty confident that it came from TCIA "pre-corrupted", and probably others in this collection are similarly corrupted. I'll notify TCIA.

**Comment by bcli4d** [comment]
It turns out that this series, and many others in this and related collections are not corrupted. David Clunie commented:
"I doubt it is corrupted,
It looks like Philips MR Raw Data, as described in their conformance statements[1].
The viewer should not be attempting to display Raw Data Storage SOP Class (1.2.840.10008.5.1.4.1.1.66) instances.
No Pixel Data is expected or required to be present."

Specifically, when the [MediaStorageSOPClassUID](MediaStorageSOPClassUID) (0002,0002) has the above value, it typically will not have pixel data and will not be displayable even though it has an MR modality. It seems that there is no unambiguous way to determine from the metadata that we get from the DICOM store (and which, by definition, does not include pixel data) whether a particular series/instance is "displayable", whatever that means.

In a separate discussion with DavidC, Steve, Andrey, I proposed that the OHIF viewer should fall back to displaying instance metadata in those cases where a series/instance instance does not have pixel or geometric data. It does this now for SRs. Steve thought this might be a good solution; waiting to hear if DavidC and/or Andrey have an opinion.

**Comment by pgundluru** [comment]
Thank You Bill, I am not able to reproduce this issue either.
