### ISSUE TITLE
In Production tier, Export to BQ fails with "unable to export cohort file" error

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#833]
Summary - There is an issue with BQ export for cohort manifest in prod. Any collection or filter currently doesn't export to BQ. The console doesn't have any error information. 

This is seen on W10 Chrome, Edge and Mac OS.

**Comment by s-paquette** [comment]
@fedorov @pgundluru Should be fixed now, try again.

**Comment by fedorov** [comment]
@s-paquette can you give a bit more details? Was this issue present earlier, or it happened sporadically? What could we have done to catch it earlier?

**Comment by s-paquette** [comment]
It happened because we don't have a v5 dataset in canceridc-data, but production has (until now) assumed that project holds the BQ datasets for export, and does, for v1-4. v5 is the first one it doesn't have. The public dataset doesn't yet have the pivot so can't be used. So for production purposes, until the public tables are updated, we have to use ETL.

Only real way to catch it is to try a series of exports after the production deployment, however I think this was moved from looking at ETL to canceridc-data more recently (due to the v6 prep) and so likely worked while it was being tested.

**Comment by fedorov** [comment]
I think this again makes the argument that after any hotfixes we must do at least minimal smoke test of the system.

**Comment by fedorov** [comment]
@pgundluru can you please help working with Suzanne and ISB team to establish the process of communication after any hotfixes are done to the production system, and develop a small set of tests that would exercise most critical aspects of the system after each hotfix.
