### ISSUE TITLE
SM series are opened in OHIF Viewer instead of Slim

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#872]
@pgundluru  / @s-paquette to add details if needed, we just discussed this today.

**Comment by pgundluru** [comment]
Issue identified by Bill on 01-28-2022

Summary: Current production webapp shows the series when you select a SM study, and when you click on the eye in the series it shows it in OHIF viewer instead of Slim viewer. 

System Reqs: Windows 10 chrome, Edge, Mac OS 

Steps to reproduce: 

1. Browse to https://portal.imaging.datacommons.cancer.gov/explore/ and select a collection e.g. CPTAC 
2. Select Filters - object class - slide microscopy images 
2. Select collection name - CPTAC-LSCC
3. Select case id - C3L-00081
4. Select study id 1.3.6.1.4.1.5962.99.1.2461659178.1421618315.1625959329834.3.0
5. View associated series https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.5962.99.1.2461659178.1421618315.1625959329834.3.0?SeriesInstanceUID=1.3.6.1.4.1.5962.99.1.2461659178.1421618315.1625959329834.2.0

**Comment by G-White-ISB** [comment]
Are both series and studies valid concepts for the SLIM viewer?

**Comment by fedorov** [comment]
@G-White-ISB can you clarify what you mean?

Adding @hackermd

**Comment by G-White-ISB** [comment]
I was asking are the pathology images organized as Series inside of Studies? But they are in all DICOM format, correct? So I presume the answer is yes.

**Comment by hackermd** [comment]
@G-White-ISB yes, the URI templates of the Slim viewer are parametrized with Study Instance UID and Series Instance UID as follows:

```none
{baseURI}/studies/{StudyInstanceUID}/series/{SeriesInstanceUID}
```

Note that these are encoded as components of the URI path and not via query parameters.

**Comment by G-White-ISB** [comment]
@hackermd - thanks!

**Comment by s-paquette** [comment]
@pgundluru Ready for testing.

**Comment by fedorov** [comment]
Slim opened in prod at series level
