### ISSUE TITLE
Study date as "Nan-NaN-NaN"

### ISSUE THREAD

**Issue by wlongabaugh** [ImagingDataCommons/IDC-WebApp#914]
**General description**
If one opens at least this TCGA pathology image, it shows a study date in Slim. But in the portal, the date is "Nan-NaN-NaN"

**Steps to reproduce the behavior**
N/A

**Screenshots**

<img width="1420" alt="Explorer-Series-Has-NAN-Date" src="https://user-images.githubusercontent.com/8441547/158705649-05621f4b-4506-4e08-a5b7-c9c88f04789f.png">

<img width="1424" alt="SeriesHasADate" src="https://user-images.githubusercontent.com/8441547/158705652-f751a4cc-ef3f-4813-bfbf-54426856bb51.png">

**Your System**
 - OS: N/A
 - Browser N/A
 - Version N/A

**Other Comments**

**Comment by wlongabaugh** [comment]
This might be relevant as well. For TCGA-COAD case TCGA-4T-AA8H, the portal shows series date "02-11-2014", but Slim shows the next day: "2014-02-12" Are these values coming from different fields?

**Comment by fedorov** [comment]
Interesting. Unfortunately, Slim does not provide a DICOM tag viewer to easily explore this, so one would need to download the files. But maybe @hackermd has thoughts on this.

**Comment by hackermd** [comment]
> This might be relevant as well. For TCGA-COAD case TCGA-4T-AA8H, the portal shows series date "02-11-2014", but Slim shows the next day: "2014-02-12" Are these values coming from different fields?

Slim shows the `StudyDate` but **not** the `SeriesDate`.

**Comment by fedorov** [comment]
Would it make sense to modify the Slim interface to say "Study date" instead of "Date"? 

The IDC portal also is presumably showing "StudyDate", so there's still discrepancy

**Comment by G-White-ISB** [comment]
The portal shows whatever is stored in SOLR for the study date. Normally there is one date. For this study there is an array of study dates in the SOLR record:
  ['2014-04-07T00:00:00Z', '2021-11-22T00:00:00Z', '2021-11-24T00:00:00Z']

This is not displayed properly in the portal, which is expecting one date.

**Comment by s-paquette** [comment]
Ah, more than one date. I was definitely not expecting that in parsing. Is this a case of bad DICOM, or can a study have more than one date? If so I need to make some adjustrments.

**Comment by wlongabaugh** [comment]
@dclunie What is going on with an array of study dates in the DCICOM file, e.g. ['2014-04-07T00:00:00Z', '2021-11-22T00:00:00Z', '2021-11-24T00:00:00Z']?

**Comment by wlongabaugh** [comment]
The case with the array is TCGA-3C-AALJ

**Comment by wlongabaugh** [comment]
@dclunie @fedorov Looking at the metadata for that case in the pivot table.
```SELECT * FROM `idc-dev-etl.idc_v8_pub.dicom_pivot_v8`
WHERE PatientID = 'TCGA-3C-AALJ';```
we have different dates in SOPInstanceUIDs belonging to the same study.

**Comment by s-paquette** [comment]
```WITH dates AS (SELECT collection_id, PatientID,StudyInstanceUID,StudyDate
FROM `idc-dev-etl.idc_v8_pub.dicom_all`
GROUP BY PatientID,StudyInstanceUID,StudyDate,collection_id
ORDER BY PatientID,StudyInstanceUID,StudyDate,collection_id)
SELECT collection_id,PatientID,StudyInstanceUID,COUNT(*)
FROM dates
GROUP BY PatientID,StudyInstanceUID,collection_id
HAVING COUNT(*) > 1
ORDER BY collection_id,PatientID,StudyInstanceUID
;```

About 391

**Comment by fedorov** [comment]
I do not know if it is required that study date is the same for all instances in the study, but in either case - it wouldn't be the first or last time where DICOM metadata does not meet the expectations. 

In general, we have two options: 1) on ingestion, fix DICOM to be compliant with the standard - this is impossible in practice; 2) adapt to the quirks in the data as we discover them. 

In this particular instance, however, the data is generated by @dclunie, so we have full control over the content. I personally do not see any reason to assign inconsistent StudyDate to the instances within a single study. If @dclunie agrees, I am sure this is trivial to fix and rerun the converter. But I doubt we would want to hold the release for that.

**Comment by fedorov** [comment]
In the general case, however, we should fix the code to deal with variable StudyDate the same way we added a workaround to deal with the variable SeriesDescription in https://github.com/ImagingDataCommons/IDC-WebApp/issues/611.

**Comment by wlongabaugh** [comment]
If we choose to show just one date in the portal, it should match Slim. @hackermd what date would you be showing if there are multiple date?

**Comment by dclunie** [comment]
When we made the decision to put all the slides for one Case into one Study, the problem with the fact that the different slides were scanned on different days needed to be addressed.

At the time I modified the script that drives the converter to at least provide the same date for all the slides, if a date is present in the SVS files, using the first date encountered, caching it, and reusing it for subsequent slides for the same case.

However, this approach fails in two circumstances:
- there is no date in the SVS file
- the date in the SVS file is in a weird format

It turns out that for this TCGA-3C-AALJ, the SVS file is from a different scanner, the SCN400, and rather than using the separate Date and Time entries in the ImageDescription TIFF tag that the Aperio scanners insert, it puts an entire datetime stamp into a single Date field - the regex I use in my script to extract the date to use as the first date fails to detect and extract this, and assumes there is no date, so it will default to the date of conversion but not remember that, which would be fine if there were not a mixture of scanners being used for the same case, leading to different dates being used :(

Interesting that the GHC extraction process and population of the BigQuery table keeps all the values as an array, rather than selecting one to keep, but a reasonable choice I suppose. Irritating that one has to be prepared to handle multiple values if present, in any query, which even though it should not happen, can happen in real world DICOM data.

Anyway, I can work around this, but I am not sure if it is worth another revision of the data before release to do so. Let me know.

PS. Strictly speaking, BTW., DICOM expects that the StudyDate is the date that the Study started, i.e., the earliest, not the first that my script encounters; that is hard to handle without two passes through all the images, one to find the earliest date and the second to use it in the conversion, which seems excessive.

**Comment by fedorov** [comment]
> Interesting that the GHC extraction process and population of the BigQuery table keeps all the values as an array, rather than selecting one to keep

No, that is not the case. Every DICOM instance corresponds to a row in BQ table after metadata is extracted. In the portal we have an additional layer of Solr, which aggregates values across instances into the series-level table. 

We already added handling of varying SeriesDescription within the instances of a series, and as we discussed today with the ISB team, should implement similar approach for the remaining attributes in the portal series table.

**Comment by wlongabaugh** [comment]
> Anyway, I can work around this, but I am not sure if it is worth another revision of the data before release to do so. Let me know.

@dclunie With 253 cases out of > 9000, we decided not to hold up the release of V8. We can version those later if we choose.

**Comment by hackermd** [comment]
I agree

**Comment by s-paquette** [comment]
@fedorov How did we want to proceed with the multiple dates? If we want to sort on the column, it can't be an array, it needs to be a single value.

**Comment by fedorov** [comment]
@s-paquette would it make sense to handle it the same way we handled variable SeriesDescriptions in https://github.com/ImagingDataCommons/IDC-WebApp/issues/611?

**Comment by s-paquette** [comment]
@fedorov For Study Description we just concatenate them. This works because the column is text, and we don't sort on it.

For the dates, if we concatenate for display they won't be sortable. So we can either display them all and not sort, or pick one and sort on that. In the case of the later we need to know how to choose the date to display and sort on.

**Comment by fedorov** [comment]
I see, thanks for the explanation. I am not sure what makes sense. Since this affects only the SM studies, I defer to the expertise of @dclunie and @hackermd for a recommendation re the desired behavior.

**Comment by dclunie** [comment]
Per the DICOM Standard, the attribute is suppose to have a value that is the start of the study, so the earliest date would be the best to choose.

**Comment by s-paquette** [comment]
Adjustment made to series and study index builder queries; a single date, the earliest, will now be pulled for index creation. Note this doesn't effect `dicom_derived_all` or `dicom_pivot`, which will continue to provide all dates on a per-instance basis, so the data isn't being lost.

**Comment by pgundluru** [comment]
![image](https://user-images.githubusercontent.com/85526819/180806190-baaa030b-985e-40df-9ccc-7afd5da4376c.png)
 

Study date in SM - Date2014-04-07

**Comment by s-paquette** [comment]
@pgundluru That's expected; the reason for the 'bug' is some of the series/studies/etc have more than one date, and we needed to choose a specific one. We're using the Most Recent date of the array.
