### ISSUE TITLE
In Test tier, When a user is signed out and clicks on a specific collection name in the collections page, there is a prompt to login  

### ISSUE THREAD

**Issue by pgundluru** [ImagingDataCommons/IDC-WebApp#919]
Summary - This was identified by Andrey on 3-25-2022, In production, a user is able to view a specific collection while not being logged in whereas in Test there is a prompt to login into IDC portal when a user clicks on any collection name.

**Comment by s-paquette** [comment]
This behavior is intentional. We require logins on test and dev because only permitted team members are allowed to use the dev and test sites. We can't easily use the AppEngine firewall as this is IP-based, and IPs change too frequently for most of the team (between remote work and dynamic addressing).
