### ISSUE TITLE
Add support of differential license collections

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#921]
We will need to support the situation where certain collections will have items that are public and limited mixed.

The level of access will be indicated in the auxiliary table at the level of instances.

When a study contains both limited and public items, study will be indicated with the mixed "eye / minus in circle" icon in the study table. When such a study is selected, the series table will indicate at the individual series level whether it is limited or public. When the user clicks on the mixed "eye / minus in circle" icon, the study will open, but the user will only see the series that are available under the public license.

We discussed that there is no conceivable use case that would justify the mix of pathology and radiology data in a single study, and decided we do not need to add support for viewing such special case studies.

This functionality will be needed for v9, and as such is marked as priority.

**Comment by fedorov** [comment]
Per discussion today, license and access will be assigned at instance level in `dicom_all`. 

Currently, license is currently assigned in the `auxiliary_metadata`, and is added to `dicom_all` from that table. `original_collections_metadata` contains single license for each collection.

With the support of differential licenses per collection, `auxiliary_metadata` will still keep per-instance license, but `original_collections_metadata` will need to keep an aggregation or an array for licenses that are encountered across the instances included in the given collection.

**Comment by bcli4d** [comment]
The v9 original_collections_metadata `licenses` field is an array of structs, each struct being a different license. The The v9 original_collections_metadata`access` field is an array of access values.

The license of an instance in auxiliary_metadata is the license of the series to which it belongs. 
If the series is from a third party (analysis result), the license is that of the corresponding analysis result.
If the series is from an original collection and the source of the data is TCIA (it's radiology data), then the license is the TCIA assigned license.
Otherwise the source is the WSI path (pathology data), and the license is the same as the license assigned by TCIA to non-redacted radiology collections in the program. I.E. the license of pathology data of a redacted collection is the license of non-redacted radiology collections in the same program).

**Comment by bcli4d** [comment]
Differential licenses are supported. Closing.
