### ISSUE TITLE
There must be mandatory columns in the manifest

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/IDC-WebApp#981]
Otherwise, the manifest will be truly useless.

Suggested mandatory columns toggled below.

For BQ manifest:

<img width="311" alt="image" src="https://user-images.githubusercontent.com/313942/171740730-db0db0a9-5366-4589-88dd-1e1b48c52fb3.png">

For file manifest:

<img width="241" alt="image" src="https://user-images.githubusercontent.com/313942/171740873-55dc4612-2ec2-476a-b778-fdcec13b7d5f.png">

(plus Access and IDC Version - see #980)

**Comment by s-paquette** [comment]
Solution: Hidden inputs which are checked, replaced those with checkbox icons which can't be unchecked.

**Comment by pgundluru** [comment]
To test this I created a cohort and exported to BQ. when I click on the manifest and am taken to GCP then I see all the suggested columns except the access (Is this because access is no longer an attribute in V12?)
![image](https://user-images.githubusercontent.com/85526819/196997980-cf8e2626-88fa-4beb-8085-ff73bf5fa7bb.png)
